RESTful_Flight_Simulator/Controllers/DisplayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RESTful_Flight_Simulator.Models;

namespace RESTful_Flight_Simulator.Controllers
{
    public class displayController : Controller
    {
        [HttpGet]
        public ActionResult DisplayLocation(string ip, int port)
        {
            displayModel model = new displayModel(ip, ""+port, null, null, null);
            return View(model);
        }

        [HttpGet]
        public ActionResult DisplayLiveRoute(string ip, int port)
        {
            displayModel model = new displayModel(ip, ""+port, null, null, null);
            return View(model);
        }

        [HttpGet]
        public ActionResult DisplaySavedRoute(string fileName, int interval)
        {

            displayModel model = new displayModel(null, null,fileName, ""+interval, null);
            return View(model);
        }
    }
}

RESTful_Flight_Simulator/Controllers/dataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text.RegularExpressions;
using RESTful_Flight_Simulator.Models;

namespace RESTful_Flight_Simulator.Controllers
{
    public class dataController : Controller
    {
        public ActionResult Index()
        {
            return View ();
        }

        [HttpGet]
        public string GetCoordinates(string vars)
        {
            List<string> list = extractVars(vars);
            string regex = "^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$";
            Match match = Regex.Match(list[0], regex, RegexOptions.IgnoreCase);

            LonLat x;
            if (match.Success)
            {
                string ip = list[0];
                int port = 5400;
                int.TryParse(list[1], out port);
                x = CoordinatesFromServer(ip, port);
            }
            else
            {
                string file = list[0];
                int index = 0;
                int.TryParse(list[1], out index);
                x = CoordinatesFromFile(file, index);
            }

            if (x != null) {
                return x.ToXml();
            }
            else {
                return LonLat.NullLonLatToXML();
            }
        }

        [HttpGet]
        public string GetCoordinatesAndSave(string vars)
        {
            List<string> l = extractVars(vars);
            // Default value
            int port = 5400;
            int.TryParse(l[1], out port);
            LonLat x = FacadeModel.GetInstance().GetCoordinatesAndSave(l[0], port, l[2]);

            if (x == null) {
                return LonLat.NullLonLatToXML();
            }
            // Else
            return x.ToXml();
        }


        private LonLat CoordinatesFromFile(string file, int index) {
            return FacadeModel.GetInstance().GetCoordinatesFromFile(file, index);

        }
        private LonLat CoordinatesFromServer(string ip, int port) {
            return FacadeModel.GetInstance().GetCoordinatesFromServer(ip, port);
        }

        private List<string> extractVars(string vars) {
            return vars.Split(',').ToList<string>();
        }
    }
}

RESTful_Flight_Simulator/Views/Display/DisplayLiveRoute.cshtml

@{
    ViewBag.Title = "DisplayLiveRoute";
}

<html>
<head>
    <link href="~/Content/StyleSheet.css" rel="stylesheet" type="text/css" />
    <script src="~/Content/JavaScript.js" type="text/javascript"></script>

</head>

<body>
    <img src="~/src/world-map.png" id="bg" alt="World Map">
    <canvas id="myCanvas"></canvas>

    <script type="text/javascript">
        document.title = "Live Route";

        var ip = '@Model.ip';
        var port = '@Model.port';

        var interval = parseInt('@Model.interval');

        var t=setInterval(start,1000.0 / interval);

        function start(){

        var input = {
            vars: `${ip},${port}`,

        };

        $.get("@Url.Action("GetCoordinates", "data")", input).done(function (data) {

            var xmlDoc = $.parseXML(data),
            $xml = $(xmlDoc),
            Lon = $xml.find("Lon").text();
            Lat = $xml.find("Lat").text();


            if(Lon.localeCompare("EOF") == 0 || Lat.localeCompare("EOF") == 0) {
                // done
                alert("done!");
                clearInterval(t);
            } else {
                drawCircle(parseFloat(Lon), parseFloat(Lat), "myCanvas");
            }
        });
            }
    </script>

</body>
</html>

RESTful_Flight_Simulator/Views/Display/DisplayLocation.cshtml

@{
    ViewBag.Title = "BaseDisplay";
}

<html>
<head>
    <link  href="~/Content/StyleSheet.css" rel="stylesheet" type="text/css" />
    <script src="~/Content/JavaScript.js" type="text/javascript"></script>

</head>

<body>
    <img src="~/src/world-map.png" id="bg" alt="World Map">
    <canvas id="myCanvas"></canvas>

    <script type="text/javascript">
        document.title = "Static Route";

        var ip = '@Model.ip';
        var port = '@Model.port';

        var interval = parseInt('@Model.interval');

        var input = {
            vars: `${ip},${port}`,

        };

        $.get("@Url.Action("GetCoordinates", "data")", input).done(function (data) {

            var xmlDoc = $.parseXML(data),
            $xml = $(xmlDoc),
            Lon = $xml.find("Lon").text();
            Lat = $xml.find("Lat").text();


            if(Lon.localeCompare("EOF") == 0 || Lat.localeCompare("EOF") == 0) {
                // done
                alert("done!");
                clearInterval(t);
            } else {
                drawCircle(parseFloat(Lon), parseFloat(Lat), "myCanvas");
            }
        });

    </script>

</body>
</html>

RESTful_Flight_Simulator/Views/Display/DisplaySavedRoute.cshtml

@{
    ViewBag.Title = "DisplaySavedRoute";
}


<html>
<head>
    <link href="~/Content/StyleSheet.css" rel="stylesheet" type="text/css" />
    <script src="~/Content/JavaScript.js" type="text/javascript"></script>

</head>

<body>
    <img src="~/src/world-map.png" id="bg" alt="World Map">
    <canvas id="myCanvas"></canvas>

    <script type="text/javascript">
        document.title = "Saved Route";
        // Define needed vars
        var i = 0;
        var fileName = '@Model.fileName';
        var interval = parseInt('@Model.interval');

        var t = setInterval(start,1000.0 / interval);

        function start()
        {
            i++;
            var input = {
                vars: `${fileName},${i}`,

            };

            $.get("@Url.Action("GetCoordinates", "data")", input).done(function (data) {

                var xmlDoc = $.parseXML(data),
                $xml = $(xmlDoc),
                Lon = $xml.find("Lon").text();
                Lat = $xml.find("Lat").text();


                if(Lon.localeCompare("EOF") == 0 || Lat.localeCompare("EOF") == 0) {
                    // done
                    alert("Done!");
                    clearInterval(t);
                } else {
                    drawCircle(parseFloat(Lon), parseFloat(Lat), "myCanvas");
                }
            });
        }
    </script>

</body>
</html>